FROM nginx:1.15
COPY index.yaml /usr/share/nginx/html
# COPY repository-0.1.0.tgz /usr/share/nginx/html
# COPY todoserver-0.1.0.tgz /usr/share/nginx/html
# COPY todoserver-0.2.0.tgz /usr/share/nginx/html
COPY *.tgz /usr/share/nginx/html/